### PR TITLE
update README

### PR DESCRIPTION
**Pull request by amirfakhrullah**
Things added:
- Quickstarts
- Installing npm packages guides

### CODE REVIEW

**Review by 12cassie34 — COMMENTED** [review]
Seems good.

**Review by abdulqshabbir — APPROVED** [review]
Looks good :)

**Review by cherylli — APPROVED** [review]
looks good

**Comment by AllMikeNoIke** [comment]
LGTM!

**Review by AllMikeNoIke — APPROVED** [review]

**Pull request merged**
