### PR TITLE
Feature/weekly schedule endpoint

### PR DESCRIPTION
**Pull request by amirfakhrullah**
## GET request `/api/courses/weekly-schedule`
- To fetch calendar data for the current week, use the endpoint without any query
- To fetch the calendar data for the previous or next week, use `prev_week_id` or `next_week_id` given in the response and pass to the endpoint as a query `weekId`
eg: `/api/courses/weekly-schedule?weekId=20220816`

### Example Response
```json
{
    "success": true,
    "data": {
        "week_id": 20220822,
        "month": "August",
        "year": "2022",
        "start_date": "21st",
        "end_date": "27th",
        "prev_week_id": 20220816,
        "next_week_id": 20220830,
        "schedules": [
            {
                "day": "monday",
                "date_label": "August 22nd",
                "date": 20220822,
                "lessons": [
                    {
                        "_id": "6303a4b7b3321d618b4540a2",
                        "name": "Physics",
                        "color": "red",
                        "start_time": "1000",
                        "end_time": "1230"
                    }
                ]
            },
            {
                "day": "tuesday",
                "date_label": "August 23rd",
                "date": 20220823,
                "lessons": [
                    {
                        "_id": "6303a8672d18b517e729e8eb",
                        "name": "Algebra 101",
                        "color": "pink",
                        "start_time": "1230",
                        "end_time": "1300"
                    },
                    {
                        "_id": "6303a4b7b3321d618b4540a3",
                        "name": "Physics",
                        "color": "red",
                        "start_time": "1300",
                        "end_time": "1600"
                    },
                    {
                        "_id": "6303a8672d18b517e729e8ec",
                        "name": "Algebra 101",
                        "color": "pink",
                        "start_time": "1330",
                        "end_time": "1500"
                    }
                ]
            },
            {
                "day": "wednesday",
                "date_label": "August 24th",
                "date": 20220824,
                "lessons": [
                    {
                        "_id": "6303a4b7b3321d618b4540a4",
                        "name": "Physics",
                        "color": "red",
                        "start_time": "0900",
                        "end_time": "1100"
                    },
                    {
                        "_id": "6303954a30de75437a4a2e53",
                        "name": "Mathematics",
                        "color": "grey",
                        "start_time": "1300",
                        "end_time": "1600"
                    },
                    {
                        "_id": "6303a8672d18b517e729e8ed",
                        "name": "Algebra 101",
                        "color": "pink",
                        "start_time": "1300",
                        "end_time": "1600"
                    }
                ]
            },
            {
                "day": "thursday",
                "date_label": "August 25th",
                "date": 20220825,
                "lessons": [
                    {
                        "_id": "6303a4b7b3321d618b4540a5",
                        "name": "Physics",
                        "color": "red",
                        "start_time": "1300",
                        "end_time": "1600"
                    }
                ]
            },
            {
                "day": "friday",
                "date_label": "August 26th",
                "date": 20220826,
                "lessons": []
            }
        ]
    }
}
```

- for time, we will be using string with this pattern => "1030", "1230", "1500" ("hhmm", 24-hour system)
- for date, we will be using number with this pattern => 20220816 (yyyymmdd)

### CODE REVIEW

**Comment by cherylli** [comment]
```
"start_date": "21st",
"end_date": "27th",
```
would it be better to juist be 

```
"start_date": 21,
"end_date":27,
```

since we'll probably need to extract the numbers for use in frontend anyway. also we need to deal with the fact that some weeks will have 2 months..

**Comment by amirfakhrullah** [comment]
@cherylli Yep I was thinking about the 2 months in a week too, I think we should probably select the month of the first day of the week to display on top here:
image

> since we'll probably need to extract the numbers for use in frontend anyway.

Okey then I will just trim out all the labels and give you guys some space to customize the data

**Comment by amirfakhrullah** [comment]
@cherylli @abdulqshabbir @12cassie34 @AllMikeNoIke 
```json
{
    "success": true,
    "data": {
        "week_id": 20220822,
        "start_date": 20220821,
        "end_date": 20220827,
        "prev_week_id": 20220816,
        "next_week_id": 20220830,
        "schedules": [
            {
                "day": "monday",
                "date": 20220822,
                "lessons": []
            },
            {
                "day": "tuesday",
                "date": 20220823,
                "lessons": [
                    {
                        "_id": "6303a8672d18b517e729e8eb",
                        "name": "Algebra 101",
                        "color": "pink",
                        "start_time": "1230",
                        "end_time": "1300"
                    },
                    {
                        "_id": "6303a4b7b3321d618b4540a3",
                        "name": "Physics",
                        "color": "red",
                        "start_time": "1300",
                        "end_time": "1600"
                    },
                    {
                        "_id": "6303a8672d18b517e729e8ec",
                        "name": "Algebra 101",
                        "color": "pink",
                        "start_time": "1330",
                        "end_time": "1500"
                    }
                ]
            },
            {
                "day": "wednesday",
                "date": 20220824,
                "lessons": [ ]
            },
            {
                "day": "thursday",
                "date": 20220825,
                "lessons": []
            },
            {
                "day": "friday",
                "date": 20220826,
                "lessons": []
            }
        ]
    }
}
```

**Comment by cherylli** [comment]
that looks good

**Review by abdulqshabbir — APPROVED** [review]
Looks good :)

**Pull request merged**
